### PR TITLE
Enhanced Readme.md

### LINKED ISSUE #215: [Feature]: Enhance Readme.md
### Describe the feature

I would like to link LISENCE file to main readme file. moreover i am aiming to enhance readme.md under gssoc by adding a feature in section, table of content, adding animation etc.
Why feature in section? - Feature in section will highlight that the project was part of gssoc in more clean, neat and representable form. I have added ss for the same, will try to create similar.
Table of content so that user have a easy navigation throughout the file

### Add ScreenShots

readmee

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSOC'24(Vinayasa Summer of Code) contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by ananyag309**
# PR Description 📜
Enhanced Readme.md
Fixes #215 

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [yes ] Documentation update
- 
## Mark the task you have completed ✅

- [✅ ] I follow [CONTRIBUTING GUIDELINE](https://github.com/Indie-Kart/ecommerce-store/blob/main/Contributing.md) & [CODE OF CONDUCT](https://github.com/Indie-Kart/ecommerce-store/blob/main/CODE_OF_CONDUCT.md) of this project.
- [✅ ] I have performed a self-review of my own code or work.
- [✅ ] I have commented my code, particularly in hard-to-understand areas.
- [ ✅] My changes generates no new warnings.
- [ ✅] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/Indie-Kart/ecommerce-store/blob/main/Contributing.md)
- [✅ ] I have added screenshot for website preview in assets/images
- [ ✅] I have added README.md in my folder

## Add your screenshots(Optional) 📸

---

### CODE REVIEW

**Comment by trishanu-init** [comment]
@ananyag309 share screenshot of ur changes

**Comment by ananyag309** [comment]
changes
changess

**Comment by ananyag309** [comment]
@trishanu-init sir do gssoc label has some points? if not please add some level label

**Comment by trishanu-init** [comment]
Yes it has some points.....we have been instructed to assign only gssoc tag for documentation changes!

**Pull request merged**
