### PR TITLE
added new feature in signup and sign in page

### LINKED ISSUE #135: Added sigin with google option and chnged style of signin and signup page
### Describe the feature

Screenshot (117)
Screenshot (116)

### Add ScreenShots

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Krishna100604**
## PR Description 📜

Fixes #135 

<hr>

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### How Has This Been Tested?

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:
 
## Mark the task you have completed ✅

- [ ] I follow [CONTRIBUTING GUIDELINE](https://github.com/Indie-Kart/ecommerce-store/blob/main/Contributing.md) & [CODE OF CONDUCT](https://github.com/Indie-Kart/ecommerce-store/blob/main/CODE_OF_CONDUCT.md) of this project.
- [ ] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/Indie-Kart/ecommerce-store/blob/main/Contributing.md)
- [ ] I have added screenshot for website preview in assets/images 
- [ ] I have added README.md in my folder 

<hr>

## Add your screenshots(Optional) 📸

--- 
<br>

### CODE REVIEW

**Comment by Krishna100604** [comment]
@trishanu-init merge this pull request

**Comment by trishanu-init** [comment]
Please attach Screenshots

**Comment by Krishna100604** [comment]
> Please attach Screenshots

Screenshot (117)
Screenshot (116)

**Comment by Krishna100604** [comment]
@trishanu-init 
done

**Comment by Krishna100604** [comment]
> have you added a signup/signin button to the navbar?

no i haven't it wasn't there  before

**Comment by trishanu-init** [comment]
> but i will add it

Okay

**Comment by trishanu-init** [comment]
Okay but you have to create that PR for sure

**Comment by Krishna100604** [comment]
> Okay but you have to create that PR for sure

okk

**Pull request merged**
