### PR TITLE
added animated cursor

### LINKED ISSUE #55: Adding the tilty effect to cards, animated cursor and customer reviews.
### Describe the feature

Animated Cursor:
Adding the animated cursor to improve the scrolling and cursing effect on different pages.
Tilty Effect:
Adding the tilty efffect on home cards and open source sections.
Customer reviews:
adding the customer eview section

### Add ScreenShots

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by happyrao78**
Closes #55 
Part 1 Completed.
Animated cursor  is added.

### CODE REVIEW

**Comment by trishanu-init** [comment]
Please link your issue with the PR using ( #issueNumber ) and follow the PR template.

**Comment by happyrao78** [comment]
> @happyrao78 Please link your issue with the PR using ( #issueNumber ) and follow the PR template.
#55 issue Completed.
1. Added animated cursor
2.Tilty effect to cards on home page
3. Customer review section at home page.

**Comment by trishanu-init** [comment]
Please attach Screenshots of changes made

**Comment by happyrao78** [comment]
> Please attach Screenshots of changes made
@trishanu-init 
Screenshot 2024-05-29 154908
Screenshot 2024-05-29 154941
Screenshot 2024-05-29 154955
Screenshot 2024-05-29 155011

**Pull request merged**
