### PR TITLE
added chatbot

### LINKED ISSUE #118: [Feature]:ChatBot
### Describe the feature

Adding the personalized chatbot to the website using react library.

### Add ScreenShots

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by happyrao78**
## PR Description 📜

Added the chatbot to the website for better user interaction.
Fixes #118 

<hr>

### Type of Change

- [ ] New feature (non-breaking change which adds functionality)

### How Has This Been Tested?
Self 

## Mark the task you have completed ✅

- [ ] I follow [CONTRIBUTING GUIDELINE](https://github.com/Indie-Kart/ecommerce-store/blob/main/Contributing.md) & [CODE OF CONDUCT](https://github.com/Indie-Kart/ecommerce-store/blob/main/CODE_OF_CONDUCT.md) of this project.
- [ ] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/Indie-Kart/ecommerce-store/blob/main/Contributing.md)
- [ ] I have added screenshot for website preview in assets/images 
- [ ] I have added README.md in my folder 

<hr>

## Add your screenshots(Optional) 📸
Screenshot 2024-06-18 205725

--- 
<br>

### CODE REVIEW

**Comment by trishanu-init** [comment]
Please include screenshots or demo video @happyrao78....

P.S  remove chat bot if you want....it's better to not have a bot than a bot that has only 3 replies

**Comment by happyrao78** [comment]
> Please include screenshots or demo video @happyrao78....
> 
> P.S remove chat bot if you want....it's better to not have a bot than a bot that has only 3 replies

I have implemented the  chatbot and the user can chat with it further more, just only the thing is you have to enter the data for the website like which are trendy products of indie kart, what is the  offer going on and etc.

**Comment by happyrao78** [comment]
> > Please include screenshots or demo video @happyrao78....
> > P.S remove chat bot if you want....it's better to not have a bot than a bot that has only 3 replies
> 
> I have implemented the chatbot and the user can chat with it further more, just only the thing is you have to enter the data for the website like which are trendy products of indie kart, what is the offer going on and etc.

It is basically sample to show you that the bot has been added. To add the custom chat to it I can raise another issue once you merge it.

**Comment by trishanu-init** [comment]
Ok , i will merge this for now.

**Comment by RushilJalal** [comment]
@happyrao78 Brother, what type of chatbot is this?
You have just added an `if` block.
Kindly do not repeat this in the future, or atleast mention how you are going to implement it.

**Pull request merged**
