### PR TITLE
feat: Update README.md fixes #45

### LINKED ISSUE #45: Readme.md_[BUG]:
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Readme.md file is good currently but it can be more fascinating by adding animated emojis , fixing allignment , adding snapshots of our project and many more small updates 

@trishanu-init assign this issue to me I will update it 
I am working under gssoc24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Meetjain1**
## PR Description 📜

Fixes #45 

<hr>

### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

### How Has This Been Tested?

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Indie-Kart/ecommerce-store/blob/main/Contributing.md) & [CODE OF CONDUCT](https://github.com/Indie-Kart/ecommerce-store/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/Indie-Kart/ecommerce-store/blob/main/Contributing.md)
<hr>

### CODE REVIEW

**Comment by Meetjain1** [comment]
@trishanu-init have a look on this pr .

**Comment by Meetjain1** [comment]
@trishanu-init have a look on this pr .

**Comment by trishanu-init** [comment]
According to the guidelines, I can't consider this PR a valid contribution hence I am closing it.

**Comment by Meetjain1** [comment]
> According to the guidelines, I can't consider this PR a valid contribution hence I am closing it.

Which guideline ? @trishanu-init

**Pull request closed without merging**
